src/app/urls.py
from django.conf import settings
from django.conf.urls import url # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('testify/', include('testify.urls')),
]

handler404 = 'app.views.error_404'
handler500 = 'app.views.error_500'
handler403 = 'app.views.error_403'
handler400 = 'app.views.error_400'

urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

src/core/urls.py
from core.views import index

from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),

]

src/testify/urls.py
from django.urls import path

from testify.views import QuestionView, TestDetailView, TestListView, TestRunnerView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:id>/', TestDetailView.as_view(), name='details'),
    path('<int:id>/start/', TestRunnerView.as_view(), name='start'),
    path('<int:id>/next/', QuestionView.as_view(), name='next'),
]

src/testify/models.py
import datetime

from accounts.models import User

from core.models import BaseModel

from django.core.exceptions import ValidationError # noqa
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'{self.name}'


class Test(models.Model):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL_CHOICES(models.IntegerChoices):
        BASIC = 0, "Basic"
        MIDDLE = 1, "Middle"
        ADVANCED = 2, "Advanced"

    topic = models.ForeignKey(to=Topic, related_name='tests', null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=64)
    description = models.TextField(max_length=1024, null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL_CHOICES.choices, default=LEVEL_CHOICES.MIDDLE)
    image = models.ImageField(default='default.png', upload_to='covers')

    def __str__(self):
        return f'{self.title}'


class Question(models.Model):
    ANSWER_MIN_LIMIT = 3
    ANSWER_MAX_LIMIT = 6

    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    order_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    text = models.CharField(max_length=64)
    description = models.TextField(max_length=512, null=True, blank=True)

    def __str__(self):
        return f'{self.text}'

    # def clean_order_number(self):
    #     order_number = self.order_number
    #
    #     # if order_number > 0 \
    #     #         and zip(((Question.objects.values_list('order_number', flat=True).last()) + 1 == order_number)
    #     #              and ((Question.objects.values_list('order_number', flat=True).order_by('-order_number'))[1] + 2
    #     #                      >= order_number)):
    #
    #     if order_number > 0 and len(Question.objects.only('id')) == order_number:
    #
    #         return order_number
    #     else:
    #         raise ValidationError('Unsorted question')
    #
    # def save(self, *args, **kwargs):
    #     self.clean_order_number()
    #
    #     super().save(*args, **kwargs)


class Answer(models.Model):
    text = models.CharField(max_length=64)
    question = models.ForeignKey(to=Question, related_name='answers', on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text}'


class TestResult(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(to=User, related_name='test_results', on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, related_name='test_results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)

    num_correct_answer = models.PositiveSmallIntegerField(default=0,
                                                          validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    num_incorrect_answer = models.PositiveSmallIntegerField(default=0,
                                                            validators=[MaxValueValidator(Test.QUESTION_MAX_LIMIT)])
    current_order_number = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(Test.QUESTION_MAX_LIMIT)])

    def points(self):
        return max(0, self.num_correct_answer - self.num_incorrect_answer)

    def time_spent(self):
        time_spent = self.write_date - self.create_date
        return time_spent - datetime.timedelta(microseconds=time_spent.microseconds)

    def score(self):
        return (self.num_correct_answer / self.test.questions.count()) * 100

    def __str__(self):
        return f'{self.test} run by {self.user.get_full_name()} at {self.write_date}'

src/testify/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, ModelForm, modelformset_factory

from testify.models import Answer, Question


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'

    def clean(self):
        pass


class AnswerAdminForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = '__all__'


class AnswerForm(ModelForm):
    is_selected = forms.BooleanField(required=False)

    class Meta:
        model = Answer
        fields = ['text', 'is_selected']


class QuestionsInlineFormSet(BaseInlineFormSet):

    def clean(self):
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError('Quantity of questions is out of range ({}..{})'.format(
                self.instance.QUESTION_MIN_LIMIT, self.instance.QUESTION_MAX_LIMIT
            ))

        order_number = []
        for form in self.forms:
            order_number.append(form.cleaned_data['order_number'])

        for question_amount, order_number in zip(range(1, len(order_number)+1), order_number):
            if question_amount != order_number:
                raise ValidationError('incorrect order')


class AnswerInlineFormSet(BaseInlineFormSet):

    def clean(self):
        if not (self.instance.ANSWER_MIN_LIMIT <= len(self.forms) <= self.instance.ANSWER_MAX_LIMIT):
            raise ValidationError('Quantity of answers is out of range ({}..{})'.format(
                self.instance.ANSWER_MIN_LIMIT, self.instance.ANSWER_MAX_LIMIT
            ))

        num_correct_answers = sum([
            1
            for form in self.forms
            if form.cleaned_data['is_correct']
        ])

        if num_correct_answers == 0:
            raise ValidationError('At LEAST one answer must be correct!')

        if num_correct_answers == len(self.forms):
            raise ValidationError('Not allowed to select ALL answers!')


AnswerFormSet = modelformset_factory(
    model=Answer,
    form=AnswerForm,
    extra=0
)

src/testify/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render # noqa
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, ListView

from testify.forms import AnswerFormSet
from testify.models import Question, Test, TestResult
from testify.services import TestRunner


class TestListView(LoginRequiredMixin, ListView):
    model = Test
    template_name = 'test.html'
    context_object_name = 'tests'
    paginate_by = 10


class TestDetailView(LoginRequiredMixin, DetailView):
    model = Test
    template_name = 'details.html'
    context_object_name = 'test'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['continue_flag'] = TestResult.objects.filter(
            user=self.request.user,
            state=TestResult.STATE.NEW,
            test=self.get_object(),
        ).count()

        best_result = TestResult.objects.filter(
            user=self.request.user,
            state=TestResult.STATE.FINISHED,
        ).extra(select={
            'points': 'num_correct_answer - num_incorrect_answer',
            'duration': 'write_date - create_date'
        }, order_by=['-points', 'duration']).first()

        if best_result is not None:
            context['best_result'] = best_result.points
            context['best_user'] = best_result.user.username

        last_run = TestResult.objects.values_list('write_date').last()
        context['last_run'] = last_run[0]

        results = TestResult.objects.all().select_related('user')
        context['results'] = results

        time_start = TestResult.objects.filter(
                    user=self.request.user,
                    state=TestResult.STATE.NEW,
                    test=self.get_object()
                ).values().last()
        if time_start is not None:
            context['time_start'] = time_start['create_date']

        return context


class TestRunnerView(LoginRequiredMixin, View):

    def get(self, request, id):  # noqa
        TestResult.objects.get_or_create(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
            defaults=dict(
                num_correct_answer=0,
                num_incorrect_answer=0,
                current_order_number=1
            )
        )

    # def get(self, request, id):  # noqa
    #     current_user_tests = TestResult.objects.filter(
    #         user=request.user,
    #         state=TestResult.STATE.NEW,
    #         test=Test.objects.get(id=id),
    #     )
    #
    #     if current_user_tests.count() == 0:
    #         TestResult.objects.create(
    #             user=request.user,
    #             state=TestResult.STATE.NEW,
    #             test=Test.objects.get(id=id),
    #             num_correct_answer=0,
    #             num_incorrect_answer=0,
    #             current_order_number=1
    #         )

        return redirect(reverse('tests:next', args=(id,)))

    @staticmethod
    def on_next(context, test_result):
        result = HttpResponse(f'Unexpected state {test_result.state}!', status=500)

        if test_result.user.popup_result == 1:
            result = context['points']
            if result == 1:
                messages.success(context['request'], 'Nice! That\'s correct answer')
            else:
                messages.warning(context['request'], 'Oops! That\'s wrong answer')

        if test_result.state == TestResult.STATE.NEW:
            result = redirect(reverse(
                'tests:next',
                args=(test_result.test.id,)
            ))

        elif test_result.state == TestResult.STATE.FINISHED:
            result = render(
                request=context['request'],
                template_name='finish.html',
                context={
                    'test_result': test_result,
                }
            )

        return result


class QuestionView(LoginRequiredMixin, View):

    def get(self, request, id):  # noqa
        test_results = TestResult.objects.filter(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
        )
        if test_results.count() == 0:
            return redirect(reverse('tests:details', args=(id,)))

        test_result = test_results.first()

        question = Question.objects.get(
            test_id=test_result.test.id,
            order_number=test_result.current_order_number
        )
        answers = question.answers.all()
        form_set = AnswerFormSet(queryset=answers)

        result = render(
            request=request,
            template_name='question.html',
            context={
                'question': question,
                'form_set': form_set,
            }
        )

        return result


    def post(self, request, id, **kwargs):  # noqa
        test_results = TestResult.objects.filter(
            user=request.user,
            state=TestResult.STATE.NEW,
            test=Test.objects.get(id=id),
        )
        if test_results.count() == 0:
            return redirect(reverse('tests:details', args=(id,)))

        test_result = test_results.first()

        form_set = AnswerFormSet(data=request.POST)

        selected_choices = [
            'is_selected' in form.changed_data
            for form in form_set.forms
        ]

        test_runner = TestRunner(
            on_next=TestRunnerView.on_next,
            test_result=test_result
        )

        result = test_runner.next(
            context={
                'request': request,
                'selected_choices': selected_choices,
            }
        )

        return result

src/testify/templates/details.html
{% extends 'base.html' %}

{% block subheader %}
    <h1>{{ test }}</h1>
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Test info</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Description</td>
                        <td>{{ test.description }}</td>
                      </tr>
                      <tr>
                        <td>Num of questions</td>
                        <td>{{ test.questions.count }}</td>
                      </tr>
                      <tr>
                        <td>Num of runs</td>
                        <td>{{ test.test_results.count }}</td>
                      </tr>
                      <tr>
                        <td>Best result</td>
                        <td> {{best_result}} (user: {{best_user}})</td>
                      </tr>
                      <tr>
                        <td>Last run</td>
                        <td>{{ last_run }}</td>
                      </tr>
                      {% if continue_flag %}
                      <tr>
                        <td>Current open run</td>
                        <td>{{ time_start }}</td>
                      </tr>
                    {% endif %}
                    </tbody>
                  </table>
            </div>
            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{{ test.image.url }}">
                </div>

                {% if continue_flag %}
                <div class="d-flex justify-content-center mt-5 mb-5" >
                        <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-warning">Continue ▶️</a>
                </div>
                {% else %}
                <div class="d-flex justify-content-center mt-5 mb-5" >
                        <a href="{% url 'tests:start' id=test.id %}" type="button" class="btn-lg btn-success">START ▶️</a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>


<table class="table table-hover" style="width:100%">
    <thead class="thead-dark">
    <tr>
        <th>#</th>
        <th>User</th>
        <th>Started</th>
        <th>Time spent</th>
        <th>Points</th>
    </tr>
    </thead>

{% for result in results %}

    <tr>
       <td>{{ forloop.counter}}</td>
       <td>{{ result.user }}</td>
       <td>{{ result.write_date }}</td>
       <td>{{ result.time_spent }}</td>
       <td>{{ result.points }}</td>
    </tr>


    {% endfor %}

</table>

{% endblock %}

src/testify/templates/finish.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load math_funcs %}

{% block subheader %}
    <h1>Congratulations!</h1>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>{{ test_result.test.title }}</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Correct answers</td>
                        <td>{{ test_result.num_correct_answer }} / {{ test_result.test.questions.count }}</td>
                    </tr>
                    <tr>
                        <td>Points</td>
                        <td>{{ test_result.points }}</td>
                      </tr>
                      <tr>
                        <td>Score</td>
                          {% expr '%1/%2*100' test_result.num_correct_answer test_result.test.questions.count as correct_answers %}
                          <td>
                              <div class="progress">
                                  <div class="progress-bar progress-bar-striped progress-bar-animated bg-success"
                                       role="progressbar" style="width: {{ test_result.score}}%"
                                       aria-valuenow="{{ correct_answers }}"
                                       aria-valuemin="0" aria-valuemax="100">
                                      {{ test_result.score|floatformat:1 }}%
                                  </div>
                                    {% expr '100 - %1' test_result.score as incorrect_answers %}
                                  <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger"
                                       style="width:{{ incorrect_answers }}%">
                                      {{ incorrect_answers }}%
                                  </div>

                              </div>
                          </td>
                      </tr>
                      <tr>
                        <td>Time finished</td>
                        <td>{{ test_result.write_date }}</td>
                      </tr>
                      <tr>
                        <td>Time spent</td>
                        <td>{{ test_result.time_spent }}</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
            <div class="col-sm">
                <div class="d-flex justify-content-center">
                    <img class="rounded-circle p-1 m-1" width="350" height="350"  src="{% static 'common/img/finish.jpg' %}">
                </div>

                <div class="d-flex justify-content-center mt-5 mb-5" >
                    <a href="{% url 'tests:list' %}" type="button" class="btn-lg btn-success">START ANOTHER TEST ▶️</a>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

src/testify/templates/leaderboard.html
{% extends 'base.html' %}

{% block title %}
    <title> Leaderboard </title>
{% endblock  %}

{% block subheader %}
<header>Leaderboard</header>
{% endblock  %}

{% block content %}

{% if user %}

<table class="table table-hover" style="width:100%">
    <thead class="thead-dark">
    <tr>
        <th>#</th>
        <th></th>
        <th>Full name</th>
        <th>Rating</th>
    </tr>
    </thead>

    {% for user in users %}
    <tr>
       <td>{{ forloop.counter }}</td>
       <td>
           <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="100" height="100" src="{{ user.image.url }}">
            </div>
       </td>

       <td>{{ user.first_name }} {{  user.last_name  }}</td>
       <td>{{ user.rating | floatformat:0 }}</td>
    </tr>
    {% endfor %}

</table>

<input type="button" class="btn btn-outline-dark" value="Close" onClick='location.href="{% url 'core:index' %}"'/>
{% else %}
<p> List is empty </p>
{% endif %}

    {% endblock %}

src/testify/templates/question.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load math_funcs %}

{% block subheader %}
    Question: <b>{{ question.text }}</b> ?

    {% expr '(%1-1)/%2*100' question.order_number question.test.questions.count as progress %}
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar" style="width: {{ progress }}%" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        Current question: {{ question.order_number }}/{{ question.test.questions.count }}
        <br>
        Possible answers:

        {{form_set.management_form}}

        {% for form in form_set %}

            <div class="mt-1">

                {{ form.is_selected }} <label>  {{ form.text.value }}</label>
            </div>

        {% endfor %}

        <div class="mt-3">
            <button type="submit" class="btn btn-success">Submit</button>

        </div>
    </form>
{% endblock %}

src/testify/templates/test.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title> Test </title>
{% endblock  %}

{% block subheader %}
<header>Test</header>
{% endblock  %}

{% block content %}

{% if tests %}

<table class="table table-hover" style="width:100%">
    <thead class="thead-dark">
    <tr>
        <th></th>
        <th>Title</th>
        <th>Description</th>
        <th>Level</th>
        <th></th>
    </tr>
    </thead>

    {% for test in tests %}
    <tr>
       <td>
           <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="100" height="100" src="{{ test.image.url }}">
            </div>
       </td>

       <td>{{ test.title }}</td>
       <td>{{ test.description }}</td>
        <td>
            <div class="d-flex justify-content-center">
                <img class="rounded-circle p-1 m-1" width="80" height="80" src="{% static 'common/img/lvl_' %}{{test.get_level_display}}.png">
            </div>
        </td>
       <td><a href="{% url 'tests:details' id=test.id %}">DETAILS</a></td>
    </tr>
    {% endfor %}

</table>
{% else %}
<p> No tests yet </p>
{% endif %}

    {% endblock %}