src/accounts/urls.py
from accounts.views import (
    AccountCreateView,
    AccountLoginView,
    AccountLogoutView,
    AccountPasswordChangeView,
    AccountUpdateView,
    ContactUsView,
    UserListView,
)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('password/', AccountPasswordChangeView.as_view(), name='change_password'),
    path('leaderboard/', UserListView.as_view(), name='leaderboard'),
    path('contact_us/', ContactUsView.as_view(), name='contact_us'),

]

src/app/urls.py
from django.conf import settings
from django.conf.urls import url # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('testify/', include('testify.urls')),
]

handler404 = 'app.views.error_404'
handler500 = 'app.views.error_500'
handler403 = 'app.views.error_403'
handler400 = 'app.views.error_400'

urlpatterns += \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

src/core/urls.py
from core.views import index

from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),

]

src/testify/urls.py
from django.urls import path

from testify.views import QuestionView, TestDetailView, TestListView, TestRunnerView

app_name = 'tests'

urlpatterns = [
    path('', TestListView.as_view(), name='list'),
    path('<int:id>/', TestDetailView.as_view(), name='details'),
    path('<int:id>/start/', TestRunnerView.as_view(), name='start'),
    path('<int:id>/next/', QuestionView.as_view(), name='next'),
]

src/templates/base.html
{% load static %}

{% url 'tests:list' as tests_list %}
{% url 'accounts:leaderboard' as accounts_leaderboard %}
{% url 'tests:#' as tests_# %}
{% url 'accounts:profile' as accounts_profile %}
{% url 'accounts:logout' as accounts_logout %}
{% url 'accounts:register' as accounts_register %}
{% url 'accounts:login' as accounts_login %}
{% url 'accounts:contact_us' as contact_us %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block title %}
    <title> Testify </title>
{% endblock  %}
{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% endblock  %}
</head>
<body>


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

  <a class="navbar-brand" href="{% url 'core:index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

       {% if request.path == tests_list %}
            <li class="nav-item active">
       {% endif %}
        <a class="nav-link" href="{% url 'tests:list' %}">Test list<span class="sr-only">(current)</span></a>
      </li>

       {% if request.path == accounts_leaderboard %}
            <li class="nav-item active">
       {% endif %}
        <a class="nav-link" href="{% url 'accounts:leaderboard' %}">Leaderboard</a>
      </li>


<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--      </li>-->
    </ul>
   <ul class="navbar-nav ">
       {% if user.is_authenticated %}
        {% include 'includes/img.html' %}

       {% if request.path == accounts_profile %}
            <li class="nav-item active">
       {% endif %}
               <a class="nav-link" href="{% url 'accounts:profile' %}"> Profile </a>
           </li>
       {% if request.path == accounts_logout %}
            <li class="nav-item active">
       {% endif %}
               <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
           </li>

       {% if request.path == contact_us %}
       <li class="nav-item active">
           {% endif %}
           <a class="nav-link" href="{% url 'accounts:contact_us' %}">Contact Us</a>
       </li>

       {% else %}
       {% if request.path == accounts_register %}
            <li class="nav-item active">
       {% endif %}
               <a class="nav-link" href="{% url 'accounts:register' %}">Sign up</a>
           </li>
       {% if request.path == accounts_login %}
            <li class="nav-item active">
       {% endif %}
               <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
           </li>
       {% endif %}

    </ul>
  </div>
</div>
</nav>
{% endblock  %}

<div class="container">

    {% include 'includes/messages.html' %}

{% block header %}
<div class="border border-success shadow-lg p-3 mb-5 m-3 bg-white rounded text-center display-4">
{% block subheader %}
    <header>
    Headers
    </header>
{% endblock  %}
</div>
{% endblock  %}

{% block content %}
{% endblock  %}

</div>
</body>
</html>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}

<head>
    {% block title %}
        <title> Home page </title>
    {% endblock %}
</head>


{% block subheader %}
<header>Home page</header>
{% endblock  %}

{% block content %}

{% endblock  %}